
# Colores de Paneles
COLOR_PANEL_SUPERIOR = "#22303C"
COLOR_PANEL_LATERAL = "#2E4756"
COLOR_PANEL_CENTRAL = "#E9EEF0"

# Anchos y Altos
ANCHO_LATERAL_ABIERTO = 155
ANCHO_LATERAL_CERRADO = 65

# Colores de Texto
COLOR_TITULO_PRINCIPAL = "#E6EDF0"
COLOR_BOTON_SELECCIONADO = "#34525E"
COLOR_BOTON_NO_SELECCIONADO = "#406675"

# Fuentes de Texto
FUENTE_TITULO = ("Segoe UI", 15, "bold")
FUENTE_BOTON_LATERAL = ("Segoe UI", 13, "bold")
FUENTE_MENU_SUPERIOR = ("Segoe UI", 12, "bold")