CREATE DATABASE AGROMON;
USE AGROMON;

CREATE TABLE PARCELAS(
	ID_PARCELA CHAR(7) NOT NULL,
	NOMBRE VARCHAR(100) NOT NULL,
	LATITUD DECIMAL(9,6) NOT NULL,
	LONGITUD DECIMAL(9,6) NOT NULL,
	TIPO_CULTIVO VARCHAR(50) NOT NULL,
	AREA DECIMAL(8,2) NOT NULL,

	CONSTRAINT PK_ID_PARCELA
		PRIMARY KEY(ID_PARCELA),
	CONSTRAINT CK_FORMATO_ID_PARCELA
		CHECK(LEN(ID_PARCELA) = 7),
	CONSTRAINT CK_LATITUD_PARCELA
		CHECK(LATITUD BETWEEN -90 AND 90),
	CONSTRAINT CK_LONGITUD_PARCELA
		CHECK(LONGITUD BETWEEN -180 AND 180),
	CONSTRAINT CK_FORMATO_TIPO_CULTIVO
		CHECK(TIPO_CULTIVO NOT LIKE '%[^A-Za-zÁÉÍÓÚáéíóúÜüÑñ ]%'),
	CONSTRAINT CK_AREA_PARCELA
		CHECK(AREA > 0)
);


CREATE TABLE DATOS_GENERALES(
	ID_PARCELA CHAR(7) NOT NULL,
	ZONA_RADICULAR DECIMAL(3,2) NOT NULL,
	EFICIENCIA_SISTEMA DECIMAL(3,2) NOT NULL,
	HUMEDAD_MINIMA DECIMAL(5,2) NOT NULL,
	HUMEDAD_MAXIMA DECIMAL(5,2) NOT NULL,
	VOL_RIEGO_DESEADO DECIMAL(4,2) NOT NULL,

	CONSTRAINT PK_ID_PARCELA_GENERALES
		PRIMARY KEY(ID_PARCELA),
	CONSTRAINT CK_ID_PARCELA_GENERALES
		CHECK(LEN(ID_PARCELA) = 7),
	CONSTRAINT FK_DATOS_GENERALES_PARCELA
		FOREIGN KEY (ID_PARCELA) REFERENCES PARCELAS(ID_PARCELA)
		ON DELETE CASCADE,
	CONSTRAINT CK_RANGOS_ZONA_RADICULAR
		CHECK(ZONA_RADICULAR BETWEEN 0.00 AND 1.00), -- EN METROS
	CONSTRAINT CK_RANGOS_EFICIENCIA_SISTEMA
		CHECK(EFICIENCIA_SISTEMA BETWEEN 0.00 AND 0.90),
	CONSTRAINT CK_HUMEDAD_MINIMA
		CHECK(HUMEDAD_MINIMA BETWEEN 0 AND 100),
	CONSTRAINT CK_HUMEDAD_MAXIMA
		CHECK(HUMEDAD_MAXIMA BETWEEN 0 AND 100),
	CONSTRAINT CK_RANGOS_HUMEDAD
		CHECK(HUMEDAD_MINIMA < HUMEDAD_MAXIMA),
	CONSTRAINT CK_RANGOS_VOL_RIEGO_DESEADO
		CHECK(VOL_RIEGO_DESEADO BETWEEN 0 AND 99)
);


CREATE TABLE TIPOS_SENSOR(
	ID_TIPO_SENSOR INT IDENTITY(1,1),
	TIPO_SENSOR VARCHAR(30) NOT NULL, -- HUMEDAD DE LA HOJA, HUMEDA DEL SUELO, TEMPERATURA
	UNIDAD_MEDIDA VARCHAR(10) NOT NULL,

	CONSTRAINT PK_ID_TIPO_SENSOR
		PRIMARY KEY(ID_TIPO_SENSOR),
	CONSTRAINT UQ_TIPO_SENSOR
		UNIQUE(TIPO_SENSOR),
	CONSTRAINT CK_FORMATO_TIPO_SENSOR
		CHECK(TIPO_SENSOR NOT LIKE '%[^A-Za-zÁÉÍÓÚáéíóúÜüÑñ ]%'),
	CONSTRAINT CK_FORMATO_TIPO_SENSOR_VALORES
		CHECK(TIPO_SENSOR IN ('Humedad de la Hoja', 'Humedad del Suelo', 'Temperatura')),
	CONSTRAINT CK_FORMATO_UNIDAD_MEDIDA
		CHECK(UNIDAD_MEDIDA IN ('Pythos 31', 'Centibares', 'Celsius')),
	CONSTRAINT CK_TIPO_SENSOR_X_UNIDAD_MEDIDA
		CHECK(
			(TIPO_SENSOR = 'Humedad de la Hoja' AND UNIDAD_MEDIDA = 'Pythos 31') OR
			(TIPO_SENSOR = 'Humedad del Suelo' AND UNIDAD_MEDIDA = 'Centibares') OR
			(TIPO_SENSOR = 'Temperatura' AND UNIDAD_MEDIDA = 'Celsius')
		)
);

INSERT INTO TIPOS_SENSOR(
	TIPO_SENSOR, UNIDAD_MEDIDA
) VALUES(
	'Humedad de la Hoja','Pythos 31'
), (
	'Humedad del Suelo','Centibares'
), (
	'Temperatura', 'Celsius'
);

CREATE TABLE ESTADOS_SENSOR(
	ID_ESTADO_SENSOR INT IDENTITY(1,1), -- ACTIVO, INACTIVO, REQUIERE REVISIÓN, EN MANTENIMIENTO
	ESTADO_SENSOR VARCHAR(30) NOT NULL,

	CONSTRAINT PK_ID_ESTADO_SENSOR
		PRIMARY KEY(ID_ESTADO_SENSOR),
	CONSTRAINT UQ_ESTADO_SENSOR
		UNIQUE(ESTADO_SENSOR),
	CONSTRAINT CK_FORMATO_ESTADO_SENSOR
		CHECK(ESTADO_SENSOR NOT LIKE '%[^A-Za-zÁÉÍÓÚáéíóúÜüÑñ ]%'),
	CONSTRAINT CK_ESTADO_SENSOR
		CHECK(ESTADO_SENSOR IN('Activo', 'Inactivo', 'Requiere Revisión', 'En Mantenimiento'))
);

INSERT INTO ESTADOS_SENSOR(ESTADO_SENSOR)
VALUES('Activo'), ('Inactivo'), ('Requiere Revisión'), ('En Mantenimiento');


CREATE TABLE SENSORES(
	ID_SENSOR CHAR(7) NOT NULL,
	ID_TIPO_SENSOR INT NOT NULL,
	ID_ESTADO_SENSOR INT NOT NULL,
	ID_PARCELA CHAR(7) NOT NULL,
	COORDENADA_X DECIMAL(9,6) NOT NULL,
	COORDENADA_Y DECIMAL(9,6) NOT NULL,
	RANGO_MINIMO DECIMAL(5,2) NOT NULL,
	RANGO_MAXIMO DECIMAL(5,2) NOT NULL,

	CONSTRAINT PK_ID_SENSOR
		PRIMARY KEY(ID_SENSOR),
	CONSTRAINT CK_FORMATO_ID_SENSOR
		CHECK(LEN(ID_SENSOR) = 7),
	CONSTRAINT FK_ID_TIPO_SENSOR_SENSORES
		FOREIGN KEY(ID_TIPO_SENSOR) REFERENCES TIPOS_SENSOR(ID_TIPO_SENSOR),
	CONSTRAINT FK_ID_ESTADO_SENSOR_SENSORES
		FOREIGN KEY(ID_ESTADO_SENSOR) REFERENCES ESTADOS_SENSOR(ID_ESTADO_SENSOR),
	CONSTRAINT DF_ID_ESTADO_SENSOR_SENSORES
		DEFAULT 1 FOR ID_ESTADO_SENSOR, -- ACTIVO
	CONSTRAINT FK_SENSORES_PARCELA
		FOREIGN KEY(ID_PARCELA) REFERENCES PARCELAS(ID_PARCELA)
		ON DELETE CASCADE,
	CONSTRAINT CK_RANGOS
		CHECK (RANGO_MINIMO < RANGO_MAXIMO)
);


CREATE TABLE CALCULOS(
	ID_CALCULO INT IDENTITY(1,1),
	ID_SENSOR CHAR(7) NOT NULL,
	ID_PARCELA CHAR(7) NOT NULL,
	A DECIMAL(8,2) NOT NULL, -- AREA DE LA PARCELA
	OACT DECIMAL(5,2) NOT NULL, -- LECTURA DEL SENSOR
	OTAR DECIMAL(4,2) NOT NULL, -- VOLUMEN DE RIEGO DESEADO
	Z DECIMAL(3,2) NOT NULL, -- ZONA RADICULAR
	N DECIMAL(3,2) NOT NULL, -- EFICIENCIA DEL SISTEMA DE RIEGO
	VREC DECIMAL(6,2) NOT NULL, -- RESULTADO: VOLUMEN DE RIEGO RECOMENDADO

	CONSTRAINT PK_ID_CALCULO
		PRIMARY KEY(ID_CALCULO),
	CONSTRAINT FK_SENSOR_CALCULOS
		FOREIGN KEY(ID_SENSOR) REFERENCES SENSORES(ID_SENSOR)
		ON DELETE CASCADE,
	CONSTRAINT FK_PARCELA_CALCULOS
		FOREIGN KEY(ID_PARCELA) REFERENCES PARCELAS(ID_PARCELA)
		ON DELETE CASCADE,
	CONSTRAINT CK_OTAR_CALCULOS
		CHECK(OTAR BETWEEN 0 AND 99),
	CONSTRAINT CK_Z_CALCULOS
		CHECK(Z BETWEEN 0.00 AND 1.00),
	CONSTRAINT CK_N_CALCULOS
		CHECK(N BETWEEN 0.00 AND 0.90)
);